export const copy = {
  product: "Codax",
  devBadge: "DEV",
  devSetupTitle: "Set up the isolated DEV profile",
  devSetupSubtitle: "This browser, account, configuration, and runtime data stay separate from the normal launcher and Codex.",
  devCoreSetup: "DEV profile",
  devStepInstall: "Initialize DEV harness",
  devStepInstallBody: "Store account capabilities in the isolated DEV home. No Codex route, Responses listener, or system service is installed; Full mode supervises only its isolated MCP tunnel.",
  devInstall: "Initialize profile",
  devReinstall: "Refresh profile",
  devMcpTitle: "Simulated tools over MCP",
  devMcpSubtitle: "Connect this separate ChatGPT account to the isolated repository harness.",
  devMcpBody: "The DEV launcher keeps its isolated MCP tunnel ready. Named repository chats attach to it and return explicit simulated receipts for tool actions.",
  devConnectorIsolationNotice: "Create a separate connector with the exact DEV name below. Keep Codex Native2 unchanged so production and repository development can run side by side.",
  devSettingsTitle: "DEV profile settings",
  devKeepRunningBody: "Keep the isolated browser session and DEV MCP tunnel available when this window closes.",
  tagline: "ChatGPT Web and Codax utilities inside the native Codex harness",
  finishWelcome: "Open launcher",
  setup: "Setup",
  activity: "Activity",
  settings: "Settings",
  workspace: "Workspace",
  configuration: "Configuration",
  runtime: "Runtime",
  browser: "Browser",
  openChatgpt: "Open ChatGPT",
  temporaryChat: "Temporary Chat",
  back: "Back",
  forward: "Forward",
  reload: "Reload",
  zoomOut: "Zoom out",
  zoomReset: "Reset zoom",
  zoomIn: "Zoom in",
  hideSidebar: "Hide sidebar",
  showSidebar: "Show sidebar",
  resizeSidebar: "Resize sidebar",
  hideTab: "Close tab",
  browserTabLimit: "Up to five simultaneous ChatGPT Web tabs. The limit avoids excessive parallel traffic on your ChatGPT account.",
  browserAddress: "ChatGPT browser",
  noActiveTask: "No active task",
  noActiveTaskBody: "ChatGPT will appear here when Codex starts a Web model turn.",
  browserReady: "Browser ready",
  showBrowser: "Show ChatGPT",
  hideBrowser: "Hide ChatGPT",
  setupTitle: "Installation",
  setupProgress: "Setup progress",
  optional: "Optional",
  required: "Required",
  stepAccount: "Sign in to ChatGPT",
  stepAccountBody: "Sign in directly in the embedded ChatGPT browser. Login stays in this launcher's private profile.",
  signIn: "Open ChatGPT to sign in",
  checkingSignIn: "Checking saved session",
  verifySignIn: "Check sign in",
  signedIn: "Signed in",
  stepSmoke: "Run browser smoke test",
  stepSmokeBody: "Select High, send a small temporary message, and verify a complete streamed response.",
  runSmoke: "Run a smoke test",
  smokePassed: "Smoke test passed",
  stepInstall: "Install into Codex",
  stepInstallBody: "Add the ChatGPT Web models without replacing Codex's native catalog. Any current custom route is saved and restored when the bridge is turned off.",
  install: "Add the models to Codex",
  reinstall: "Repair Codex setup",
  awaitingCodex: "Restart Codex",
  restartCodex: "Restart Codex once to refresh the model picker.",
  mcpTitle: "Native Codex tools over MCP",
  mcpSubtitle: "Connect ChatGPT to the active Codex harness through an OpenAI tunnel.",
  mcpBody: "Let every available ChatGPT Web effort, including Pro, use the active Codex harness.",
  configureMcp: "Configure MCP",
  mcpReady: "MCP configured",
  close: "Close",
  previous: "Back",
  next: "Next",
  done: "Done",
  guideVideo: "Guide video",
  mcpStepOne: "Create a tunnel and API key",
  mcpStepOneBody: "Create an OpenAI tunnel, copy its Tunnel ID, and create a regular API key with Tunnels Read + Use (free; the key is required only to run the tunnel). (Don't forget to create a ChatGPT workspace.)",
  openTunnels: "Open Tunnels",
  openKeys: "Create API key",
  mcpStepTwo: "Connect the local harness",
  mcpStepTwoBody: "Paste the Tunnel ID and API key. The tunnel must belong to the same OpenAI account that will use the ChatGPT plugin. The key stays in private local storage and is never written to launcher logs.",
  mcpStepTwoHint: "You can add the MCP connector in ChatGPT only after this step succeeds and the tunnel is running.",
  mcpCatalogRequired: "Connect harness is unavailable until the Codex models are installed and verified. Return to Setup, click Install models, restart Codex once, and wait for the model catalog check to complete.",
  tunnelId: "Tunnel ID",
  runtimeKey: "API key (not Admin key)",
  connect: "Connect harness",
  reconnect: "Reconnect harness",
  credentialsConfigured: "Tunnel credentials saved",
  credentialsConfiguredBody: "The launcher will reuse the private Tunnel ID and API key already stored on this device.",
  replaceCredentials: "Replace credentials",
  keepCredentials: "Keep saved credentials",
  mcpStepThree: "Attach the ChatGPT connector",
  mcpStepThreeBody: "Before creating the connector, enable Developer Mode in ChatGPT Settings. In ChatGPT Plugins, create a new connector, choose Tunnel, select the tunnel you created, set Authentication to None, and use the exact connector name shown below. Open Permissions and choose Allow low-risk actions. The connector advertises its gateway tools as non-destructive so organization policies that block Allow all actions can still permit them; the outer Codex harness still enforces its sandbox and approvals. Then verify the runtime.",
  connectorMigrationNotice: "Upgrading from Codex Native? Leave the old connector untouched and create Codex Native2 as a new connector. Do not rename or refresh Codex Native. Verify runtime rejects a legacy-only setup.",
  openConnectors: "Open ChatGPT Plugins",
  connectorName: "Connector name",
  verifyRuntime: "Verify runtime",
  activityTitle: "Runtime activity",
  activitySubtitle: "Local diagnostics. Export a privacy-safe copy before sharing; raw logs stay on this device.",
  recentActivity: "Recent events",
  noLogs: "No runtime events yet.",
  exportSafeLog: "Export safe log",
  settingsTitle: "Launcher settings",
  general: "General",
  launchAtLogin: "Launch at login",
  launchAtLoginBody: "Keep the local Responses route available before Codex opens.",
  keepRunningOnClose: "Keep server running when window closes",
  keepRunningOnCloseBody: "Hide the launcher in the system tray so native and ChatGPT Web models remain available.",
  showDuringTurns: "Show browser during turns",
  showDuringTurnsBody: "Reveal the embedded ChatGPT surface whenever a browser turn is active.",
  disableBrowserWorkarounds: "Disable ChatGPT browser workarounds",
  disableBrowserWorkaroundsBody: "Allow ChatGPT to load its Sidebar and background requests. Applies immediately.",
  diagnostics: "Diagnostics",
  runDoctor: "Run doctor",
  cancelTurns: "Cancel active Codex turn",
  cancelTurnsBody: "Abort the active HTTP stream and its retained ChatGPT browser turn.",
  turnsCancelled: "Active Codex turn cancelled",
  uninstallIntegration: "Remove Codex integration",
  uninstallIntegrationBody: "Restore the previous Codex model route and remove the private bridge runtime.",
  integrationRemoved: "Integration removed; restart Codex once",
  running: "Running",
  complete: "Complete",
  failed: "Failed",
  healthy: "Healthy",
  needsAttention: "Needs attention",
  loading: "Loading",
  platform: "Platform",
  version: "Version",
  status: "Status",
  notConfigured: "Not configured",
  error: "Something went wrong",
  dismiss: "Dismiss",
  sessionReminderTitle: "Refresh your ChatGPT session",
  sessionReminderBody: "We recommend signing in again every two days. A stale ChatGPT session can interrupt Web model turns and MCP tools.",
  logOut: "Log out",
} as const;

export type Copy = typeof copy;
